# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-11 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formacao', models.CharField(max_length=200)),
                ('experiencia', models.CharField(max_length=200)),
                ('infos', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('nome', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=50)),
                ('cpf', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaga', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=200)),
                ('salario', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='curriculo',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rhfun.Pessoa'),
        ),
    ]
